// eslint-disable
// this is an auto generated file. This will be overwritten

export const getRecords = `query GetRecords($agent: String, $prizm: Int, $make: String) {
  getRecords(agent: $agent, prizm: $prizm, make: $make) {
    months {
      name
      year
      month
      estimate
      twelveMonths
      records
      obs_cancel_0
      obs_cancel_1
      obs_cancel_2
      obs_cancel_3
      obs_cancel_4
      obs_cancel_5
      obs_cancel_6
      est_cancel_0
      est_cancel_1
      est_cancel_2
      est_cancel_3
      est_cancel_4
      est_cancel_5
      est_cancel_6
      obs_cancel_0_cnt
      obs_cancel_1_cnt
      obs_cancel_2_cnt
      obs_cancel_3_cnt
      obs_cancel_4_cnt
      obs_cancel_5_cnt
      obs_cancel_6_cnt
      est_cancel_0_cnt
      est_cancel_1_cnt
      est_cancel_2_cnt
      est_cancel_3_cnt
      est_cancel_4_cnt
      est_cancel_5_cnt
      est_cancel_6_cnt
    }
    total {
      name
      year
      month
      estimate
      twelveMonths
      records
      obs_cancel_0
      obs_cancel_1
      obs_cancel_2
      obs_cancel_3
      obs_cancel_4
      obs_cancel_5
      obs_cancel_6
      est_cancel_0
      est_cancel_1
      est_cancel_2
      est_cancel_3
      est_cancel_4
      est_cancel_5
      est_cancel_6
      obs_cancel_0_cnt
      obs_cancel_1_cnt
      obs_cancel_2_cnt
      obs_cancel_3_cnt
      obs_cancel_4_cnt
      obs_cancel_5_cnt
      obs_cancel_6_cnt
      est_cancel_0_cnt
      est_cancel_1_cnt
      est_cancel_2_cnt
      est_cancel_3_cnt
      est_cancel_4_cnt
      est_cancel_5_cnt
      est_cancel_6_cnt
    }
    estimate {
      name
      year
      month
      estimate
      twelveMonths
      records
      obs_cancel_0
      obs_cancel_1
      obs_cancel_2
      obs_cancel_3
      obs_cancel_4
      obs_cancel_5
      obs_cancel_6
      est_cancel_0
      est_cancel_1
      est_cancel_2
      est_cancel_3
      est_cancel_4
      est_cancel_5
      est_cancel_6
      obs_cancel_0_cnt
      obs_cancel_1_cnt
      obs_cancel_2_cnt
      obs_cancel_3_cnt
      obs_cancel_4_cnt
      obs_cancel_5_cnt
      obs_cancel_6_cnt
      est_cancel_0_cnt
      est_cancel_1_cnt
      est_cancel_2_cnt
      est_cancel_3_cnt
      est_cancel_4_cnt
      est_cancel_5_cnt
      est_cancel_6_cnt
    }
    twelveMonths {
      name
      year
      month
      estimate
      twelveMonths
      records
      obs_cancel_0
      obs_cancel_1
      obs_cancel_2
      obs_cancel_3
      obs_cancel_4
      obs_cancel_5
      obs_cancel_6
      est_cancel_0
      est_cancel_1
      est_cancel_2
      est_cancel_3
      est_cancel_4
      est_cancel_5
      est_cancel_6
      obs_cancel_0_cnt
      obs_cancel_1_cnt
      obs_cancel_2_cnt
      obs_cancel_3_cnt
      obs_cancel_4_cnt
      obs_cancel_5_cnt
      obs_cancel_6_cnt
      est_cancel_0_cnt
      est_cancel_1_cnt
      est_cancel_2_cnt
      est_cancel_3_cnt
      est_cancel_4_cnt
      est_cancel_5_cnt
      est_cancel_6_cnt
    }
  }
}
`;
